name: student_buddy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  splash_screen_view: ^3.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - splashscreen_image.png
    - assets/login_image.png
    - assets/



splash_screen_view:
  color: "#ffffff"
  image: assets/splashscreen_image.png




